### ISSUE TITLE
File "/home/ali/src/NAOChat/gpt.py", line 1, in <module>

### ISSUE THREAD

**Issue by varozhan3212** [SkylarWiderski/Pepper_Chat_GPT#1]
hi

when i run the gpy.py  getting the error  ~/Pepper_Chat_GPT$ python3.11 gpt.py
Traceback (most recent call last):
  File "/home/ali/Pepper_Chat_GPT/gpt.py", line 1, in <module>
    from lwe import ApiBackend
ModuleNotFoundError: No module named 'lwe'

what i am missing ?!?

**Comment by jesusazogue** [comment]
Same here

**Comment by fazni** [comment]
@varozhan3212 @jesusazogue do you have any clue ?
